apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-telemetry-webui
  labels:
    app: f1-telemetry
spec:
  replicas: 1
  template:
    metadata:
      name: f1-telemetry-webui
      labels:
        app: f1-telemetry-webui
    spec:
      containers:
        - name: f1-telemetry-webui
          image: ppatierno/f1-telemetry-webui:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: f1-telemetry-webui
