name: Build
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo Hello, Formula 1 Telemetry Kafka!
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        java-version: '11'
      - name: Build with Maven
        run: mvn package